apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack-pro:latest
        ports:
        - containerPort: 4566
          name: localstack
        env:
        - name: LOCALSTACK_API_KEY
          value: "ls-qiKU4916-BUgI-9759-CitI-JiXOFowO23f6"
        - name: DEBUG
          value: "1"
        - name: SERVICES
          value: "s3,sns,sqs"
        - name: DATA_DIR
          value: "/var/lib/localstack"
        - name: PERSISTENCE
          value: "1"
        - name: LAMBDA_EXECUTOR
          value: "local"
        - name: LOCALSTACK_HOSTNAME
          value: "localstack"
        - name: HOSTNAME_EXTERNAL
          value: "localstack.default.svc.cluster.local"
        readinessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 60
          periodSeconds: 30
        volumeMounts:
        - name: localstack-data
          mountPath: /var/lib/localstack
      volumes:
      - name: localstack-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: default
spec:
  selector:
    app: localstack
  ports:
  - port: 4566
    targetPort: 4566
    name: localstack
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-secret
  namespace: default
type: Opaque
data:
  # LocalStack API key (base64 encoded)
  api-key: bHMtcWlLVTQ5MTYtQlVnSS05NzU5LUNpdEktSmlYT0Zvd08yM2Y2
