apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "localstack.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    name: localstack
  type: {{ .Values.service.type }}
