name: idp-demo

replicaCount: 1

image:
  repository: python
  pullPolicy: IfNotPresent
  tag: "3.11-slim"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""

# LocalStack configuration
localstack:
  enabled: true
  endpoint: "http://host.minikube.internal:4566"
  region: us-east-1

# AWS resources configuration
s3:
  bucketName: "hello-world-bucket"
  
sns:
  topicName: "hello-world-notifications"
  
sqs:
  queueName: "hello-world-queue"