apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: localstack-aws-secret
      key: creds
  endpoint:
    hostnameImmutable: true
    services: [iam, s3, sns, sqs, sts]
    url:
      type: Static
      static: "{{ .Values.localstack.endpoint }}"
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-aws-secret
  namespace: default
type: Opaque
stringData:
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
