apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.s3.bucketName }}
spec:
  forProvider:
    region: {{ .Values.localstack.region }}
    forceDestroy: true
  providerConfigRef:
    name: localstack-config
