apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: {{ .Values.sns.topicName }}
spec:
  forProvider:
    name: {{ .Values.sns.topicName }}
    region: {{ .Values.localstack.region }}
  initProvider: {}
  managementPolicies:
  - "*"
  providerConfigRef:
    name: localstack-config
