apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: {{ .Values.sns.topicName }}
spec:
  forProvider:
    region: {{ .Values.localstack.region }}
    tags: {}
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: localstack-config
