apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Application instanceLabelKey
  application.instanceLabelKey: argocd.argoproj.io/instance
  # Git repositories
  repositories: |
    - url: https://github.com/argoproj/argocd-example-apps.git
  # Server configuration
  server.insecure: "true"
  # Enable gRPC-Web
  server.grpc.web: "true"