apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///Users/alex/repos/localstack
    targetRevision: HEAD
    path: helm/hello-world-app
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.pullPolicy
          value: Never
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true