apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: {{ .Values.rds.dbName }}
spec:
  forProvider:
    dbInstanceClass: {{ .Values.rds.instanceClass }}
    dbName: {{ .Values.rds.dbName }}
    engine: {{ .Values.rds.engine }}
    engineVersion: {{ .Values.rds.engineVersion | quote }}
    username: admin
    passwordSecretRef:
      name: db-password
      key: password
      namespace: default
    allocatedStorage: {{ .Values.rds.allocatedStorage }}
    storageType: gp2
    region: {{ .Values.localstack.region }}
    publiclyAccessible: true
    skipFinalSnapshot: true
    deleteAutomatedBackups: true
  providerConfigRef:
    name: localstack-config
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: default
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
