apiVersion: sns.aws.upbound.io/v1beta1
kind: Topic
metadata:
  name: {{ .Values.sns.topicName }}
spec:
  forProvider:
    name: {{ .Values.sns.topicName }}
    region: {{ .Values.localstack.region }}
  providerConfigRef:
    name: localstack-config
---
apiVersion: sns.aws.upbound.io/v1beta1
kind: TopicSubscription
metadata:
  name: {{ .Values.sns.topicName }}-subscription
spec:
  forProvider:
    protocol: sqs
    endpoint: arn:aws:sqs:{{ .Values.localstack.region }}:000000000000:{{ .Values.sqs.queueName }}
    region: {{ .Values.localstack.region }}
    topicArnRef:
      name: {{ .Values.sns.topicName }}
  providerConfigRef:
    name: localstack-config
