replicaCount: 1

image:
  repository: localstack/localstack-pro
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 4566
  targetPort: 4566

# LocalStack configuration
localstack:
  apiKey: ""
  debug: "1"
  services: "s3,sns,sqs"
  dataDir: "/var/lib/localstack"
  persistence: "1"
  lambdaExecutor: "local"
  hostname: "localstack"
  hostnameExternal: "localstack.default.svc.cluster.local"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""
